dist: trusty
language: rust
services: docker
sudo: required

matrix:
  include:
    - env: TARGET=arm-unknown-linux-gnueabi
    - env: TARGET=armv7-unknown-linux-gnueabihf

before_install:
  - set -e
  - rustup self update
  - rustup toolchain install nightly
  - rustup default nightly

after_script: set +e

install: echo "Install"
script: echo "Script"

notifications:
  email:
    on_success: never
